"""Human-facing markdown renderer for the audit Report."""

from __future__ import annotations

from pathlib import Path

from claude_stack_audit.models import Finding, Report, Severity

_SEV_LABEL = {
    Severity.CRITICAL: "Critical",
    Severity.HIGH: "High",
    Severity.MEDIUM: "Medium",
    Severity.LOW: "Low",
    Severity.INFO: "Info",
}


def _md_escape(s: str) -> str:
    """Escape characters that would break a GFM pipe table cell."""
    return s.replace("|", r"\|").replace("`", r"\`")


def render(report: Report) -> str:
    parts: list[str] = []
    parts.extend(_render_header(report))
    parts.extend(_render_summary(report))

    # Treat INFO-only as "nothing actionable" — renders the happy-path message
    # rather than a silent gap. INFO rendering (full inventory section) is
    # deferred to phase 2.
    actionable = [f for f in report.findings if f.severity is not Severity.INFO]
    if not actionable:
        parts.append("_No findings. The stack is clean._")
        parts.append("")
    else:
        parts.extend(_render_findings_sections(report))

    parts.extend(_footer(report))
    return "\n".join(parts)


def _render_header(report: Report) -> list[str]:
    return [
        f"# Claude Stack Audit — {report.generated_at.date().isoformat()}",
        "",
        f"**Health score: {report.scorecard.score} / 1000**",
        "",
    ]


def _render_summary(report: Report) -> list[str]:
    lines = [
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|------:|",
    ]
    for sev in Severity:
        lines.append(f"| {_SEV_LABEL[sev]} | {report.scorecard.counts.get(sev, 0)} |")
    lines.append("")
    return lines


def _render_findings_sections(report: Report) -> list[str]:
    lines: list[str] = []
    crit = [f for f in report.findings if f.severity is Severity.CRITICAL]
    if crit:
        lines.append("## Critical findings")
        lines.append("")
        lines.extend(_finding_table(crit))

    for sev in (Severity.HIGH, Severity.MEDIUM, Severity.LOW):
        bucket = [f for f in report.findings if f.severity is sev]
        if not bucket:
            continue
        lines.append(f"## {_SEV_LABEL[sev]} findings")
        lines.append("")
        lines.extend(_finding_table(bucket))
    return lines


def _finding_table(findings: list[Finding]) -> list[str]:
    out = [
        "| ID | Layer | Criterion | Artifact | Message | Fix hint |",
        "|----|-------|-----------|----------|---------|----------|",
    ]
    for f in findings:
        artifact = _md_escape(f.artifact)
        message = _md_escape(f.message)
        hint = _md_escape(f.fix_hint) if f.fix_hint else ""
        out.append(
            f"| {f.check_id} | {f.layer.value} | {f.criterion.value}"
            f" | `{artifact}` | {message} | {hint} |"
        )
    out.append("")
    return out


def _footer(report: Report) -> list[str]:
    ts = report.generated_at.isoformat(timespec="minutes")
    tools = (
        ", ".join(f"{k} {v}" for k, v in sorted(report.external_tool_versions.items())) or "none"
    )
    return [
        "---",
        f"_Generated by cstack-audit {report.tool_version} at {ts} · tools: {tools}_",
    ]


def write(report: Report, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(report), encoding="utf-8")
