"""Human-facing markdown renderer for the audit Report."""

from __future__ import annotations

from pathlib import Path

from claude_stack_audit.models import Finding, Report, Severity

_SEV_LABEL = {
    Severity.CRITICAL: "Critical",
    Severity.HIGH: "High",
    Severity.MEDIUM: "Medium",
    Severity.LOW: "Low",
    Severity.INFO: "Info",
}


def render(report: Report) -> str:
    """Render a Report to a Markdown string."""
    parts: list[str] = []
    parts.extend(_render_header(report))
    parts.extend(_render_summary(report))

    if not report.findings:
        parts.append("_No findings. The stack is clean._")
        parts.append("")
    else:
        parts.extend(_render_findings_sections(report))

    # phase 1: Inventory rendering deferred
    parts.append(_footer(report))
    return "\n".join(parts)


def _render_header(report: Report) -> list[str]:
    return [
        f"# Claude Stack Audit — {report.generated_at.date().isoformat()}",
        "",
        f"**Health score: {report.scorecard.score} / 1000**",
        "",
    ]


def _render_summary(report: Report) -> list[str]:
    lines = [
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|------:|",
    ]
    for sev in Severity:
        lines.append(f"| {_SEV_LABEL[sev]} | {report.scorecard.counts.get(sev, 0)} |")
    lines.append("")
    return lines


def _render_findings_sections(report: Report) -> list[str]:
    lines: list[str] = []
    crit = [f for f in report.findings if f.severity is Severity.CRITICAL]
    if crit:
        lines.append("## Critical findings")
        lines.append("")
        lines.extend(_finding_table(crit))

    for sev in (Severity.HIGH, Severity.MEDIUM, Severity.LOW):
        bucket = [f for f in report.findings if f.severity is sev]
        if not bucket:
            continue
        lines.append(f"## {_SEV_LABEL[sev]} findings")
        lines.append("")
        lines.extend(_finding_table(bucket))
    return lines


def _finding_table(findings: list[Finding]) -> list[str]:
    out = [
        "| ID | Layer | Criterion | Artifact | Message | Fix hint |",
        "|----|-------|-----------|----------|---------|----------|",
    ]
    for f in findings:
        row = (
            f"| {f.check_id} | {f.layer.value} | {f.criterion.value}"
            f" | `{f.artifact}` | {f.message} | {f.fix_hint or ''} |"
        )
        out.append(row)
    out.append("")
    return out


def _footer(report: Report) -> str:
    ts = report.generated_at.isoformat(timespec="minutes")
    tools = ", ".join(f"{k} {v}" for k, v in sorted(report.external_tool_versions.items()))
    return f"\n---\n_Generated by cstack-audit {report.tool_version} at {ts} · tools: {tools}_\n"


def write(report: Report, path: Path) -> None:
    """Write a rendered report to a file, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(report))
